### ISSUE TITLE
bump R version requirement or switch from native to magrittr pipes

### ISSUE THREAD

**Issue by bbolker** [amoneva/cacc#1]
See https://stackoverflow.com/questions/79012479/unable-to-install-r-package-cacc .

If you want to use native R pipes you should specify R >=4.1 in your DESCRIPTION file; otherwise you could globally replace `|>` to `%>%` and import the pipe from `magrittr` ...

**Comment by amoneva** [comment]
Thank you for bringing this to my attention. I appreciate the feedback and the link to the StackOverflow post. I will address this by updating the `DESCRIPTION` file to specify `R (>= 4.1)` for native pipe usage. I’ll push a fix as soon as possible.
